### ISSUE TITLE
Fix - JSON parsing of Consent Requests/Responses

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-flutter#150]
Original issue in tiki-sdk-ios:

```
In the example app, the TikiSdkConsent shows the same value for `path` and `uses` in the destination. I

Acceptance criteria:
1 -  The HTTP method is in `uses` and the URL without schema in `path`.
```

Updated issue added in https://github.com/tiki/tiki-sdk-flutter/issues/150#issuecomment-1422597698

When decoding JSON to TikiSdkDestination in the ReqConsent* classes, the paths are been used in place of the uses.

A similar issue was fixed before in https://github.com/tiki/tiki-sdk-flutter/issues/102#issuecomment-1360199148.

Acceptance criteria:
1 - All Req/Rsp Consent classes correctly parse JSON
2 - add tests to `integration_test/tiki_sdk_flutter_platform_test.dart` with specific paths and uses for methods `modifyConsent`, `getConsent` and `applyConsent`.

**Comment by Harshit933** [comment]
We have to change the decoding:

From this : ***List? uses = map["destination"]?["paths"];***
to this: ***List? uses = map["destination"]?["uses"];***


in all the files where the decoding of paths is assigned to uses

**Comment by ricardobrg** [comment]
> We have to change the decoding:
> 
> From this : _**List? uses = map["destination"]?["paths"];**_ to this: _**List? uses = map["destination"]?["uses"];**_
> 
> in all the files where the decoding of paths is assigned to uses. Is this what we have to do?

yes, that's the fix.

To test the different types of `uses` and `paths`, you could copy the [getConsent]() and [applyConsent]() tests for the following scenarios:

1 - getConsent: use TikiSdkDestination(["path/to/test"], uses: ["use case to test"]) instead of TikiSdkDestination.all() in `modifyConsent` method and check if the return of getConsent gives the same path and use case.
2 - applyConsent: use TikiSdkDestination(["path/to/test"], uses: ["use case to test"]) instead of TikiSdkDestination.all() in `modifyConsent`method and use applyConsent to check if it matches.

**Comment by Harshit933** [comment]
@ricardobrg What kind of values should I be taking for uses list in TikiSdkDestination?

**Comment by ricardobrg** [comment]
@Harshit933 
> What kind of values should I be taking for uses list in TikiSdkDestination?
You can create them locally in the tests. Doesn't need to be a field in the class. But if you rather do that, it's ok too. You choose.
> Also I have corrected all the paths and uses conflicts which were there in the req and res classes should I make the PR?
Sure! Please do the PR when you are done. If you still want to work on the code you can create the PR as a draft and I will review when you are done. Please, add me as a reviewer in the PR. Thanks!

**Comment by Harshit933** [comment]
Created the PR. Please review it and let me know which things are needed to be changed

**Comment by ricardobrg** [comment]
![Image](https://user-images.githubusercontent.com/8357343/219148386-51a1e6e7-b4c5-4450-8467-e9abefd4322b.png)
