### ISSUE TITLE
Example app - Create Cupertino home screen UI

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-flutter#153]
Create the Flutter version of the iOS Example App home screen.

This should be a Stateless Widget that will hold other widgets and keep their state.

For the Widgets that uses another screen to change values (Wallet, Destination, and Body), it should use the [Navigator.pop method](https://docs.flutter.dev/cookbook/navigation/returning-data) to return the updated value.

Acceptance criteria:
1 - Working screen with the same UI from iOS

**Comment by ricardobrg** [comment]
![image](https://user-images.githubusercontent.com/8357343/219387195-a806af9c-ae65-499a-bcdd-a48ec5a05c98.png)

**Comment by ricardobrg** [comment]
![Image](https://user-images.githubusercontent.com/8357343/219388290-b0ee0ee4-761c-4628-a68c-ba24b5f38efa.png)

**Comment by ricardobrg** [comment]
> ![Image](https://user-images.githubusercontent.com/8357343/219388290-b0ee0ee4-761c-4628-a68c-ba24b5f38efa.png)

@Harshit933 we need to update the example app Home UI to match this screenshot. The business logic described in the first comment was done in #194. This issue is just to update the UI.

**Comment by Harshit933** [comment]
Got it!

**Comment by ricardobrg** [comment]
@Harshit933 I am holding this because this code is moving to another repository soon. Before I move it, I will merge in a branch and update the changes needed to finish this PR. Thanks for waiting!

**Comment by Harshit933** [comment]
Not at all a problem. Merge it whenever you feel so.
