### ISSUE TITLE
TIKI SDK Buttons

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-flutter#201]
Border: 1px, accent color, 10px radius
Padding: 16px 32px
size: 190x60px
weight: medium
font size: 20pt
 

Flat btn colors 
- bg: #fff
- font: primaryColor

Color btn colors
- bg: accentColor
- font: #fff

Parameters:
  - accentColor, 
  - primaryColor, 
  - type (flat/color)
  - text
  - callback

**Comment by gantanikhilraj** [comment]
is it done? if not can assign to me

**Comment by ricardobrg** [comment]
@gantanikhilraj assigned!

Please create it as a widget in lib/ui folder

**Comment by gantanikhilraj** [comment]
> @gantanikhilraj are you on our discord server? https://discord.gg/tiki

Yes, thanks for the invitation. Could you brief me about the issue.

**Comment by ricardobrg** [comment]
@gantanikhilraj 

This is a Stateless Widget that will build the Button for TIKI SDK UI. It will be reused in all UIs and needs to receive 4 parameters: primaryColor, accentColor, text, callback

The button will have:
Border: 1px, accent color, 10px radius
Padding: 16px vertical 32px horizontal (minimum)
size: 190x60px
font: Space Grotesk
font weight: medium
font size: 20pt

It will use two named constructors: 
- flat 
  - backgroundColor: #FFFFFF
  - font color: primaryColor
  - border color: accentColor
 
- color
  - backgroundColor: accentColor
  - font color: #FFFFFF
  - border color: accentColor
  
onTap action should call the callback parameter.

**Comment by ricardobrg** [comment]
@gantanikhilraj I am building #196 and did the UI for these buttons. Are you working on it already? If not, may I grab this? We can find another issue for you.

**Comment by gantanikhilraj** [comment]
> @gantanikhilraj I am building #196 and did the UI for these buttons. Are you working on it already? If not, may I grab this? We can find another issue for you.

Okay, you can complete this.

**Comment by ricardobrg** [comment]
![Image](https://user-images.githubusercontent.com/8357343/220995840-5c34df16-53a4-4b87-a483-fbe61f7aac9d.png)
