### ISSUE TITLE
bug: settings method of the TikiSdk

### ISSUE THREAD

**Issue by Harshit933** [tiki/tiki-sdk-flutter#257]
reference https://github.com/tiki/examples/pull/6#issuecomment-1529627450

**Comment by ricardobrg** [comment]
quoting the original comment

> When we trigger the opt out button in the settings method of the offer the onAccept() functionality of the offer works as mentioned in the lib/home_screen.dart. Also Opt in button triggers the functionality of the onDecline() method. This should not happen I guess. (Probably a bug?)

**Comment by ricardobrg** [comment]
Adding to Sprint 70 for investigation.

**Comment by ricardobrg** [comment]
The variables were switched. Done in #264
