### ISSUE TITLE
Add customizable callback option to TikiSdk.present() method

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-flutter#262]
As a developer, I would like to have the option to create personalized flows for each TikiSdk.present() method call. This would allow me to react differently to user choices and provide a better user experience.

The `TikiSdk.present()` method does not provide any customizable options for the user experience flow. The only available options are the `onAccept`/`onDecline` callbacks, which are applied to all calls of the method and are best suitable for license and offer management.

To achieve this, I suggest adding an optional callback or return method to the `TikiSdk.present()` method. This would allow the developer to decide what to do next in each call of the method, making it especially useful when working with multiple offer prompts in different areas of the app.

**Comment by mike-audi** [comment]
Decided to not over complicate the SDK, given the developer has a variety of options to implement multi-state endings already. 

Such as:

- use a state variable (e.g. sharedPreferences or similar) set prior to calling `present()` and then retrieving this var in the onAccept/onDecline handlers.  

- wrap the `present()` function in an async method/thread and then inline await for it's completion.
