### ISSUE TITLE
Incorrect spelling of App Tracking on Error Screen

### ISSUE THREAD

**Issue by mike-audi** [tiki/tiki-sdk-flutter#267]
When failing to request the app tracking permission, the permission is misspelt or more specifically it's missing spaces.

![Image](https://user-images.githubusercontent.com/3769672/236728060-87be0869-265b-4d62-b48f-d6a095336003.png)

**Comment by mike-audi** [comment]
ideally it should read "tracking"

**Comment by Harshit933** [comment]
@mike-audi should it read "tracking" only or "app tracking transparency" would work?
